### Create User
POST http://localhost:3000/user/create
content-type: application/json

{
    "firstName":"user",
    "lastName":"Kumar",
    "userName":"user@test.com",
    "gender":"male",
    "dob":"19/07/1999"
}


###Get all User
GET http://localhost:3000/user?username=nathu@test.com

###Get a particular user
GET http://localhost:3000/user/2