### Create User
POST http://localhost:3000/user/create
content-type: application/json

{
    "firstName":"Naveen",
    "lastName":"Kumar",
    "userName":"naveen@test.com",
    "gender":"male",
    "dob":"19/07/1999"
}


###
GET http://localhost:3000/user?username=nathu@test.com